### ISSUE TITLE
Can't use Primal Wave as on click spell

### ISSUE THREAD

**Issue by asteingass** [enderneko/Cell#202]
Hi, if I put Primal Wave as a click cast on a hotkey and hover over a frame, it won't work. Nothing happens.
Happens in the current WoW Build 11.x

**Comment by enderneko** [comment]
this should have been fixed two weeks ago
0c59fadf12bf085f14d02b33881fe78d5a5ca1f4

**Comment by asteingass** [comment]
Hmm still not working for me, if I hover over the spell it says "shadowlands". I've never played shadowlands, but I know there are some different covenants, do I need to chage it?

**Comment by enderneko** [comment]
just tested on a newly created Shaman
![image](https://github.com/user-attachments/assets/b2406db3-0439-4eb9-9439-92294bd791d6)
no issue found

**Comment by enderneko** [comment]
and read this
https://www.wowhead.com/spell=375982/primordial-wave#comments:id=5484251

**Comment by stratohe** [comment]
I got it working using my own custom makro "/cast [@mouseover, help, nodead] Urzeitliche Welle(Schattenlande)"

![image](https://github.com/user-attachments/assets/7ff00907-bd9e-4448-b84a-1e355a129e0a)

I use the german Interface and the character was transferred from Remix. Did already switch the covenants. Mabee an localization error in the WoW Client?

**Comment by enderneko** [comment]
```lua
if t[3] == 428332 then
    spellName = spellName .. "(" .. EXPANSION_NAME8 .. ")"
end
```
found the cause
just tested on EN and CN
but on DE, EXPANSION_NAME8 is in EN, this is the problem

**Comment by enderneko** [comment]
solve method found
```lua
local name, subName = C_SpellBook.GetSpellBookItemName(FindSpellBookSlotBySpellID(428332), Enum.SpellBookSpellBank.Player)
```
use the subName

**Comment by enderneko** [comment]
solve method found
```lua
local spell = Spell:CreateFromSpellID(428332)

spell:ContinueOnSpellLoad(function()
      local name = spell:GetSpellName()
      local subName = spell:GetSpellSubtext()
      print(name, subName)
end)
```
use `subName`

**Comment by peekaybee** [comment]
I still have the issue .. I play an OLD shaman that WAS originally the Necrolords. I have changed to every faction but my spell book still says Primordial Wave is Shadowlands. Using the link above I created a macro to call THAT version of the spell. It casts with a hard cast but cannot be called with ANY frame or mouseover and it doesnt trigger latest WA timers etc. 

I suspect the issue is with older shaman .. I dont know how we fix that but its not unique to Cell sorry.

**Comment by peekaybee** [comment]
> /cast [@mouseOver, help, nodead] Urzeitliche Welle(Schattenlande)

Correction .. this hover over macro works so long as you dont try to call it from Cell.

**Comment by stratohe** [comment]
> > /cast [@mouseOver, help, nodead] Urzeitliche Welle(Schattenlande)
> 
> Correction .. this hover over macro works so long as you dont try to call it from Cell.

Mh i have a fully working solution:

![image](https://github.com/user-attachments/assets/e8167ce3-83a8-4d58-97c4-c72beb1e1f35)

Works very well. Maybee you have some space between spellname and braces

The string directly copied:

/cast [@mouseover, help, nodead] Urzeitliche Welle(Schattenlande)

**Comment by peekaybee** [comment]
Righto. Deleted Cell. Cleaned up config and related files. Reinstalled and reconfigured. Used the macro as provided. It all works now. 🤷 

Sorry .. and thanks for taking the time to help/respond. All good using the macro .. although a spell fix would be good.

**Comment by astronaute77** [comment]
I had the same problem, in english the custom skill is simply:
`/cast [@mouseOver, help, nodead] Primordial Wave(Shadowlands)`

**Comment by dambros** [comment]
Same issue for me. I can't use lay on hands, Intercession or Redemption on my protection paladin. It works for holy, but not prot.
